version: "3.9"
services:
  db:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    ports:
      - 5432:5432
  api:
   build: api/
   ports:
     - 8000:8000
   depends_on:
     - db
